# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rey's ACA Blog!
email: yodlan@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  My first blog. Career change later in life. 
baseurl: "/aca-blog" # the subpath of your site, e.g. /blog
url: "http://yodlan.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  yodlan


---
layout: post
title: "Second post!"
date: 2016-05-16 13:32:00 -0600
categories: coding
---


# Build settings
markdown: kramdown


